name: Weekly Dependencies

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  weekly-deps:
    name: Weekly Dependencies
    uses: HoneyDrunkStudios/HoneyDrunk.Actions/.github/workflows/nightly-deps.yml@main
    with:
      dotnet-version: '10.0.x'
      runs-on: 'ubuntu-latest'
      working-directory: 'HoneyDrunk.Web.Rest'
      project-path: './HoneyDrunk.Web.Rest.slnx'
      check-dotnet-deps: true
      create-update-prs: false
      actions-ref: 'main'
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
